### ISSUE TITLE
Projenin ilk cercevesini olusturmak

### ISSUE THREAD

**Issue by cagataycali** [ilteriskeskin/cevrimici-kitap-galerisi#1]
Projede direkt kod yazabilmemiz icin ilk cerceveyi olusturup issue olarak yapilmasini on gordugun isleri acabilir misin?

**Comment by ilteriskeskin** [comment]
Hemmen dosyaları oluşturup pushlayayım :)

**Comment by cagataycali** [comment]
Ellerine saglik, ufak bir sekilde koda girisi hazirlayabilirsen direkt ilk mentee ben olacagim

**Comment by cagataycali** [comment]
-Benim hatam- olusturmussun abi!
