### ISSUE TITLE
Tasarım dosyalarının düzenlenmesi

### ISSUE THREAD

**Issue by ilteriskeskin** [ilteriskeskin/cevrimici-kitap-galerisi#13]
Tasarım dosyalarında yeni tasarım templates/Frontend içinde ve onların render_template()'e eklenmesi ve dosya yollarının düzeltilmesi gerekiyor.

**Comment by selcuktatar** [comment]
Bu task benim tarafimdan yapildi ancak git konusunda problem yasiyorum.
